apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: docker.io/mongo
      ports:
      - containerPort: 27017
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: mongo-root-username
      - name: MONGO_INITDB_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: mongo-root-password
      volumeMounts:
        - name: volume-db
          mounthPath: /data/db
  volumes:
    - name: volume-db
      persistentVolumeClaim:
        claimName: pvc-db
        

            
