kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: scc-developer
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- developer
- admin
