apiVersion: v1
kind: Pod
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  containers:
  - name: mongo-express
    image: docker.io/mongo-express
    ports:
    - containerPort: 8081
    env: 
    - name: ME_CONFIG_MONGODB_ADMINUSERNAME
      valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: mongo-root-username
    - name: ME_CONFIG_MONGODB_ADMINPASSWORD
      valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: mongo-root-password
    - name: ME_CONFIG_MONGODB_SERVER
      value: