apiVersion: v1
kind: Pod
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  containers:
  - name: mongo-express
    image: docker.io/mongo-express
    ports:
    - containerPort: 8081
    env: 
    -name:
    - name: MONGODB_ADMINUSERNAME
      valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: mongo-root-username
    - name: ME_CONFIG_MONGODB_ADMINPASSWORD
      valueFrom:
          secretKeyRef:
            name: mongodb
            key: database-password
    - name: ME_CONFIG_MONGODB_SERVER
      valueFrom:
        configMapKeyRef:
          name: mongodb-configmap
          key: database_url