apiVersion: v1
kind: Pod
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo
      ports:
      - containerPort: 27017
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: mongo-root-username
      - name: MONGO_INITDB_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: mongo-root-password
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /data/db
        name: db-volume   
      volumes:
      - name: db-volume
        host-path:
          path: /cluster/data/db  
            

            
