apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongodb-service
  name: mongodb-service
spec:
  selector:
    app: mongodb 
  ports:
  - port: 27010
    protocol: TCP 
    targetPort: 27010